### PR TITLE
Added "proxies" argument to _HTTPConnection.__init__() to allow proxy support

### PR DESCRIPTION
**Pull request by mikekhusid**

### CODE REVIEW

**Comment by gtback** [comment]
@mikekhusid , before I merge this, can you sign the [OASIS TC Open Repository CLA](https://www.oasis-open.org/resources/open-repositories/cla)? If this is a problem, let me know and we can figure something else out.

**Comment by mikekhusid** [comment]
@gtback Signed the agreement, it's pending approval.  Thanks for reviewing the pull request quickly!

**Comment by robincover** [comment]
Re: before I merge this...  the CLA was filed, all clear

https://www.oasis-open.org/resources/open-repositories/cla/view-individual

Contributor Name: Mikhail Khusid

    Contributor Email: mikekhusid@gmail.com
    Github Username: mikekhusid

**Comment by gtback** [comment]
Thanks @robincover and @mikekhusid !

**Pull request merged**
