### PR TITLE
WIP: Issue 24, TODOS, and others

### PR DESCRIPTION
**Pull request by emmanvg**
The reason I still consider this WIP is because we still haven't acquired consensus over:

- Accept the current design
    - That is, to allow `url`, `password`, `verify` and the `conn` object. Note that, if you provide `conn` all other positional parameters are not used and vice-versa.
- Change the design
    - Allow one of both options: `To only use the HTTPConnection object (potentially exposing it for usage)` or `Only use url, password and verify to create the connection internally`.

### CODE REVIEW

**Comment by emmanvg** [comment]
Related #24 #26

**Comment by emmanvg** [comment]
This PR includes the following enhancements aside from the related issues:
- Implemented the `#TODO` messages left in the code. Mostly validation of responses.
- Format and change docstrings to Google Style

**Comment by emmanvg** [comment]
@gtback, I finished making all the changes I had in mind.

**Comment by gtback** [comment]
In the future, let's try to make smaller PRs that each only address one issue :)

**Pull request merged**
