### PR TITLE
Session Bugfix and Enhancement

### PR DESCRIPTION
**Pull request by spencer-hanson**
I Fixed connection bug in Server, where when you retrieve the api_roots in refresh(), it would use self._user and self._password, even if you provided a connection object. I removed _user and _password, and let it just default to using _conn, a connection object, since it's created anyways in super(). 
This bug appeared when you use authentication and provide your own _HTTPConnection object.

I also added session support to _HTTPConnection, adding the option to use a given session object instead of creating one. This allows for custom authentication and proxy use.

### CODE REVIEW

**Comment by gtback** [comment]
Hi @spencer-hanson . Thanks for the pull request. 

The current implementation is intentional. We don't want to share a connection between a Server and its API Roots, since it's possible that a Server will point to API Roots on a different hostname (though whether that's a valid concern or worth keeping separate is debatable). We have been changing this around quite a bit lately, and I don't think any of us are completely satisfied with the current approach, though. 

Do you have any ideas or suggestions on how other libraries handle this? We've thought about forcing user to build their own HTTP Connection and pass it in, rather than allowing user/password/etc. which is more straightforward but requires more code from users.

**Comment by spencer-hanson** [comment]
Hey @gtback, I think it would make sense to have a 'mapping' of HTTPConnections, that you can pass into a TAXIIEndpoint object, which would have a url and a session to use for that url, with a default to fall back to. This way you can pass in a 'HTTPConnectionMap' or HTTPConnection, and get rid of username and password completely. This way you can have a separate connection to each API Root, and only require minimal code.
If you think this is a good solution, I'll go ahead and implement it in this pull request.

**Comment by gtback** [comment]
Thanks, @spencer-hanson. Can you tell me a bit more about what you're trying to do? I've been operating under the assumption that people don't often need to do Server Discovery in the same operation as querying API Roots or Collections. There's nothing wrong with a solution like what you describe, but I'm trying to keep this library as small and tidy as possible, without adding complexity except where warranted by common use cases.

**Comment by gtback** [comment]
Hi @spencer-hanson, I think we're going to do something like this in order to fix #37. If you're able to fix the conflict, I'll merge this in, otherwise I'll incorporate it when we get to #37.

**Comment by spencer-hanson** [comment]
Closing since it will be included in #37

**Pull request closed without merging**
